file settings:
  columns:
    history_new:
    - one_m_system_load_average
    - cluster_association_time
    - cluster_connectivity
    - cluster_dissociation_time
    - cluster_name
    - cluster_peer_count
    - cluster_state
    - cluster_version
    - contact
    - cpu_count
    - disk_space_free
    - disk_space_total
    - former_cluster_association_time
    - former_cluster_connectivity
    - former_cluster_dissociation_time
    - former_cluster_name
    - former_cluster_peer_count
    - former_reward_state
    - former_timestamp_index
    - ip
    - id
    - last_notified_timestamp
    - latest_cluster_session
    - latest_version
    - layer
    - name
    - node_cluster_session
    - node_peer_count
    - wallet_address
    - wallet_balance
    - notify
    - p2p_port
    - public_port
    - reward_false_count
    - reward_state
    - reward_true_count
    - state
    - timestamp_index
    - version
    subscribers_new:
    - date
    - id
    - name
    - contact
    - ip
    - public_port
    - layer
    - type
  dtypes:
    history_new:
      cluster_association_time: float
      cluster_connectivity: str
      cluster_dissociation_time: float
      cluster_name: str
      cluster_peer_count: float
      cluster_state: str
      cluster_version: str
      contact: str
      cpu_count: float
      disk_space_free: float
      disk_space_total: float
      former_cluster_association_time: str
      former_cluster_connectivity: str
      former_cluster_dissociation_time: float
      former_cluster_name: str
      former_cluster_peer_count: float
      former_reward_state: bool
      former_timestamp_index: datetime64[ns]
      id: str
      ip: str
      last_notified_timestamp: datetime64[ns]
      latest_cluster_session: float
      latest_version: str
      layer: float
      name: str
      node_cluster_session: str
      node_peer_count: float
      notify: bool
      one_m_system_load_average: float
      p2p_port: float
      public_port: float
      reward_false_count: float
      reward_state: bool
      reward_true_count: float
      state: str
      timestamp_index: datetime64[ns]
      version: str
      wallet_address: str
      wallet_balance: float
    subscribers_new:
      contact: str
      date: str
      id: str
      ip: str
      layer: int
      name: str
      public_port: int
      type: str
  locations:
    archived history: assets/data/historic/archived
    cluster modules: assets/src/cluster modules
    db: assets/data/db/db.sqlite3
    historic temp: assets/data/historic/temp
    history_new: assets/data/historic/latest
    log: assets/data/logs/bot/exec.log
    subscribers temp: assets/data/users/temp
    subscribers_new: assets/data/users/db
general:
  loop_init_time: '12:25:00'
  loop_interval_minutes: 5
  name: Hgtp Node Spidr
  notifications:
    free disk space sleep (hours): 6
    free disk space threshold (percentage): 10
    reward state sleep (minutes): 10
  public release: false
  request retry (count): 3
  request retry interval (sec): 1
  request timeout (sec): 6
  version: 5-alpha.1
modules:
  mainnet:
    0:
      be:
        info:
          latest snapshot: global-snapshots/latest
        url:
        - https://be-mainnet.constellationnetwork.io
      id: 8b0f8889948b35ac122a44d7a597f461a1c813fb74a75aa9af04de7fe4a070e8e68e8ef3c72b3b5952ec4a238827fba580350a655fc445375cf99688d506f9d7
      info:
        cluster: cluster/info
        metrics: metrics
        node: node/info
      rewards: true
      url:
      - https://l0-lb-mainnet.constellationnetwork.io
    1:
      id: 5a8f0f756659be91e8af0b6aa1e2a63a94227680aa4d565e055a37db206f69a3b88479e7f37e8c9c9eca40278ddc98eab2b07f0fc0cf17fdf83ca012082ba827
      info:
        cluster: cluster/info
        metrics: metrics
        node: node/info
      rewards: false
      url:
      - https://l1-lb-mainnet.constellationnetwork.io
  testnet:
    0:
      be:
        info:
          latest snapshot: global-snapshots/latest
        url:
        - https://be-testnet.constellationnetwork.io
      id: 048e867de007559fda3b82798fb092fd680d958d9b2dd79dd95202bc48a5a20ee30efefbe602d417553b510e53f834329b94f54b3c188ab2aa496fb537ea9f87
      info:
        cluster: cluster/info
        metrics: metrics
        node: node/info
      rewards: true
      url:
      - https://l0-lb-testnet.constellationnetwork.io
    1:
      id: 890a641e239763187f1a8c3a30d1bbb23a57eb4a82b1d69154540376c8045dd94c1e0be08ebeeb43cf6b0f7de6cefa6a418e2f53dfa53ddcf7afd293a34ee363
      info:
        cluster: cluster/info
        metrics: metrics
        node: node/info
      rewards: false
      url:
      - https://l1-lb-testnet.constellationnetwork.io
tessellation:
  github:
    releases:
      latest: repos/constellation-labs/tessellation/releases/latest
    url: https://api.github.com
