file settings:
  locations:
    cluster modules: assets/src/cluster_modules
    db: assets/data/db/database.db
    log: assets/data/logs/bot/exec.log
general:
  loop_init_time: '12:25:00'
  loop_interval_minutes: 1
  name: Hgtp Node Spidr
  notifications:
    free disk space sleep (hours): 6
    free disk space threshold (percentage): 10
    reward state sleep (minutes): 10
  public release: false
  request retry (count): 3
  request retry interval (sec): 1
  request timeout (sec): 6
  version: 5-alpha.1
modules:
  integrationnet:
    0:
      be:
        info:
          latest snapshot: global-snapshots/latest
        url:
        - https://be-integrationnet.constellationnetwork.io
      id: 9aa906e7ce99e972833fc231fcadee444e576030a1eb2b5bc749d805eabc12aa1f84a89af4d694238b71127456a790fb5c4eff22fc80e44a8310731a35c46f22
      info:
        cluster: cluster/info
        metrics: metrics
        node: node/info
      rewards: true
      url:
      - https://l0-lb-integrationnet.constellationnetwork.io
    1:
      id: 29b0dc8d310b0403db818db2da8d187127cdce14a825d3176534b03537e8573eaff0f95366617074996322d64f52b7a62e2737d77f7fbc888accbf4b98f7f651
      info:
        cluster: cluster/info
        metrics: metrics
        node: node/info
      rewards: false
      url:
      - https://l1-lb-integrationnet.constellationnetwork.io
  mainnet:
    0:
      be:
        info:
          latest snapshot: global-snapshots/latest
        url:
        - https://be-mainnet.constellationnetwork.io
      id: e0c1ee6ec43510f0e16d2969a7a7c074a5c8cdb477c074fe9c32a9aad8cbc8ff1dff60bb81923e0db437d2686a9b65b86c403e6a21fa32b6acc4e61be4d70925
      info:
        cluster: cluster/info
        metrics: metrics
        node: node/info
      rewards: true
      url:
      - https://l0-lb-mainnet.constellationnetwork.io
    1:
      id: 710b3dc521b805aea7a798d61f5d4dae39601124f1f34fac9738a78047adeff60931ba522250226b87a2194d3b7d39da8d2cbffa35d6502c70f1a7e97132a4b0
      info:
        cluster: cluster/info
        metrics: metrics
        node: node/info
      rewards: false
      url:
      - https://l1-lb-mainnet.constellationnetwork.io
  testnet:
    0:
      be:
        info:
          latest snapshot: global-snapshots/latest
        url:
        - https://be-testnet.constellationnetwork.io
      id: 154311944d97be83d18d37fcc3c8e7bb20cd8fa2c97e9e736f402f2614b112aa3d9ff57d6aa27b8aed82fe74b26c98c300e41b67c2c20c8d0cb1458f487adbd8
      info:
        cluster: cluster/info
        metrics: metrics
        node: node/info
      rewards: true
      url:
      - https://l0-lb-testnet.constellationnetwork.io
    1:
      id: 9561959b0b4410e263fa9d0e25ee2bfeb9a1362db6680ceef242b11f5f18e98457b1191478e5901153c9dbb6eb5eca09924d9ab210017dd203bab5816ff88567
      info:
        cluster: cluster/info
        metrics: metrics
        node: node/info
      rewards: false
      url:
      - https://l1-lb-testnet.constellationnetwork.io
tessellation:
  github:
    releases:
      latest: repos/constellation-labs/tessellation/releases/latest
    url: https://api.github.com
