file settings:
  locations:
    archived history: assets/data/historic/archived
    cluster modules: assets/src/cluster_modules
    db: assets/data/db/db.sqlite3
    historic temp: assets/data/historic/temp
    history_new: assets/data/historic/latest
    log: assets/data/logs/bot/exec.log
    subscribers temp: assets/data/users/temp
    subscribers_new: assets/data/users/db
general:
  loop_init_time: '12:25:00'
  loop_interval_minutes: 1
  name: Hgtp Node Spidr
  notifications:
    free disk space sleep (hours): 6
    free disk space threshold (percentage): 10
    reward state sleep (minutes): 10
  public release: false
  request retry (count): 3
  request retry interval (sec): 1
  request timeout (sec): 6
  version: 5-alpha.1
modules:
  mainnet:
    0:
      be:
        info:
          latest snapshot: global-snapshots/latest
        url:
        - https://be-mainnet.constellationnetwork.io
      id: b34e87be784c61fe0b3a93460fb923eccfd39edf7031127dbefe2546c45d7c70b17e90b8baf0e05125065da4206cbc36ff99cc33293aa232d8def138c31a2fd1
      info:
        cluster: cluster/info
        metrics: metrics
        node: node/info
      rewards: true
      url:
      - https://l0-lb-mainnet.constellationnetwork.io
    1:
      id: 5a8f0f756659be91e8af0b6aa1e2a63a94227680aa4d565e055a37db206f69a3b88479e7f37e8c9c9eca40278ddc98eab2b07f0fc0cf17fdf83ca012082ba827
      info:
        cluster: cluster/info
        metrics: metrics
        node: node/info
      rewards: false
      url:
      - https://l1-lb-mainnet.constellationnetwork.io
  testnet:
    0:
      be:
        info:
          latest snapshot: global-snapshots/latest
        url:
        - https://be-testnet.constellationnetwork.io
      id: 154311944d97be83d18d37fcc3c8e7bb20cd8fa2c97e9e736f402f2614b112aa3d9ff57d6aa27b8aed82fe74b26c98c300e41b67c2c20c8d0cb1458f487adbd8
      info:
        cluster: cluster/info
        metrics: metrics
        node: node/info
      rewards: true
      url:
      - https://l0-lb-testnet.constellationnetwork.io
    1:
      id: 890a641e239763187f1a8c3a30d1bbb23a57eb4a82b1d69154540376c8045dd94c1e0be08ebeeb43cf6b0f7de6cefa6a418e2f53dfa53ddcf7afd293a34ee363
      info:
        cluster: cluster/info
        metrics: metrics
        node: node/info
      rewards: false
      url:
      - https://l1-lb-testnet.constellationnetwork.io
tessellation:
  github:
    releases:
      latest: repos/constellation-labs/tessellation/releases/latest
    url: https://api.github.com
