file settings:
  columns:
    history_new:
    - one_m_system_load_average
    - cluster_association_time
    - cluster_connectivity
    - cluster_dissociation_time
    - cluster_name
    - cluster_peer_count
    - cluster_state
    - cluster_version
    - contact
    - cpu_count
    - disk_space_free
    - disk_space_total
    - former_cluster_association_time
    - former_cluster_connectivity
    - former_cluster_dissociation_time
    - former_cluster_name
    - former_cluster_peer_count
    - former_reward_state
    - former_timestamp_index
    - ip
    - id
    - last_notified_timestamp
    - latest_cluster_session
    - latest_version
    - layer
    - name
    - node_cluster_session
    - node_peer_count
    - wallet_address
    - wallet_balance
    - notify
    - p2p_port
    - public_port
    - reward_false_count
    - reward_state
    - reward_true_count
    - state
    - timestamp_index
    - version
    subscribers_new:
    - date
    - id
    - name
    - contact
    - ip
    - public_port
    - layer
    - type
  dtypes:
    history_new:
      cluster_association_time: float
      cluster_connectivity: str
      cluster_dissociation_time: float
      cluster_name: str
      cluster_peer_count: float
      cluster_state: str
      cluster_version: str
      contact: str
      cpu_count: float
      disk_space_free: float
      disk_space_total: float
      former_cluster_association_time: str
      former_cluster_connectivity: str
      former_cluster_dissociation_time: float
      former_cluster_name: str
      former_cluster_peer_count: float
      former_reward_state: bool
      former_timestamp_index: datetime64[ns]
      id: str
      ip: str
      last_notified_timestamp: datetime64[ns]
      latest_cluster_session: float
      latest_version: str
      layer: float
      name: str
      node_cluster_session: str
      node_peer_count: float
      notify: bool
      one_m_system_load_average: float
      p2p_port: float
      public_port: float
      reward_false_count: float
      reward_state: bool
      reward_true_count: float
      state: str
      timestamp_index: datetime64[ns]
      version: str
      wallet_address: str
      wallet_balance: float
    subscribers_new:
      contact: str
      date: str
      id: str
      ip: str
      layer: str
      name: str
      public_port: int
      type: str
  locations:
    archived history: assets/data/historic/archived
    cluster modules: assets/code/cluster modules
    historic temp: assets/data/historic/temp
    history_new: assets/data/historic/latest
    log: assets/data/logs/bot/exec.log
    subscribers temp: assets/data/users/temp
    subscribers_new: assets/data/users/db
general:
  loop_init_time: '12:25:00'
  loop_interval_minutes: 5
  name: Hgtp Node Spidr
  notifications:
    free disk space sleep (hours): 6
    free disk space threshold (percentage): 10
    reward state sleep (minutes): 10
  public release: false
  request retry (count): 3
  request retry interval (sec): 1
  request timeout (sec): 6
  version: 5-alpha.1
modules:
  mainnet:
    0:
      be:
        info:
          latest snapshot: global-snapshots/latest
        url:
        - https://be-mainnet.constellationnetwork.io
      id: ec3e25065181aa5bda7fd9ca22a13e2a59688ac0762b5a61022fd42b0943d1d468b86a517222479456d0770d50c99cbd517045a9ba3a4ee1968534e30a785e69
      info:
        cluster: cluster/info
        metrics: metrics
        node: node/info
      rewards: true
      url:
      - https://l0-lb-mainnet.constellationnetwork.io
    1:
      id: 3f5ac775fa4f20dba1f5912562789b9c3ea38df28c347c2fe81800d07a494b6e0d263db1b1d08b58750fb34d503c6f84c50f7db26b14eaeb41c732e4eac4fb54
      info:
        cluster: cluster/info
        metrics: metrics
        node: node/info
      rewards: false
      url:
      - https://l1-lb-mainnet.constellationnetwork.io
  testnet:
    0:
      be:
        info:
          latest snapshot: global-snapshots/latest
        url:
        - https://be-testnet.constellationnetwork.io
      id: 154311944d97be83d18d37fcc3c8e7bb20cd8fa2c97e9e736f402f2614b112aa3d9ff57d6aa27b8aed82fe74b26c98c300e41b67c2c20c8d0cb1458f487adbd8
      info:
        cluster: cluster/info
        metrics: metrics
        node: node/info
      rewards: true
      url:
      - https://l0-lb-testnet.constellationnetwork.io
    1:
      id: cd6362aeee3ffb3b209bb3f1459848624e8bd9e66cb22e82a8cb7c08d02a833e74e3becc1fce804b1233773e24baf178f17e2c9611c39758abe8cb2ad4d20558
      info:
        cluster: cluster/info
        metrics: metrics
        node: node/info
      rewards: false
      url:
      - https://l1-lb-testnet.constellationnetwork.io
tessellation:
  github:
    releases:
      latest: repos/constellation-labs/tessellation/releases/latest
    url: https://api.github.com
