file settings:
  locations:
    cluster modules: assets/src/cluster modules
    db: assets/data/db/database.db
    log: assets/data/logs/bot/exec.log
general:
  loop_init_time: '12:00:00'
  loop_interval_minutes: 1
  name: Hgtp Node Spidr
  notifications:
    free disk space sleep (hours): 6
    free disk space threshold (percentage): 10
    reward state sleep (minutes): 10
  public release: false
  request retry (count): 3
  request retry interval (sec): 1
  request timeout (sec): 6
  version: 5-alpha.1
modules:
  integrationnet:
    0:
      be:
        info:
          latest snapshot: global-snapshots/latest
        url:
        - https://be-integrationnet.constellationnetwork.io
      id: 6bdd56d3b7f9d73b36064bf4aab77a2576f8f8f50c5591d60cc762f91be24a64062dd8c2144ce5e68e9d982e1f8dce57471ae02b053fe62946ca66ba8723df8c
      info:
        cluster: cluster/info
        metrics: metrics
        node: node/info
      rewards: true
      url:
      - https://l0-lb-integrationnet.constellationnetwork.io
    1:
      id: 340f081474e91d5402133bae99d9a9bb9e92933984081be23e3b06701c11087b460c0cd6973b1b8fcc15a68297de62d34d2b73603696fad872d2eac0443ca3bc
      info:
        cluster: cluster/info
        metrics: metrics
        node: node/info
      rewards: false
      url:
      - https://l1-lb-testnet.constellationnetwork.io
  mainnet:
    0:
      be:
        info:
          latest snapshot: global-snapshots/latest
        url:
        - https://be-mainnet.constellationnetwork.io
      id: a6adc12761e752903102cdd088ef61a62f7c0bc131350b93f5fe5a68f43400df707b1075bf0adcc24c18992270e77a92ee5e1e2c1fa2cb267f5b6077eef0df82
      info:
        cluster: cluster/info
        metrics: metrics
        node: node/info
      rewards: true
      url:
      - https://l0-lb-mainnet.constellationnetwork.io
    1:
      id: 5a8f0f756659be91e8af0b6aa1e2a63a94227680aa4d565e055a37db206f69a3b88479e7f37e8c9c9eca40278ddc98eab2b07f0fc0cf17fdf83ca012082ba827
      info:
        cluster: cluster/info
        metrics: metrics
        node: node/info
      rewards: false
      url:
      - https://l1-lb-mainnet.constellationnetwork.io
  testnet:
    0:
      be:
        info:
          latest snapshot: global-snapshots/latest
        url:
        - https://be-testnet.constellationnetwork.io
      id: 154311944d97be83d18d37fcc3c8e7bb20cd8fa2c97e9e736f402f2614b112aa3d9ff57d6aa27b8aed82fe74b26c98c300e41b67c2c20c8d0cb1458f487adbd8
      info:
        cluster: cluster/info
        metrics: metrics
        node: node/info
      rewards: true
      url:
      - https://l0-lb-testnet.constellationnetwork.io
    1:
      id: 340f081474e91d5402133bae99d9a9bb9e92933984081be23e3b06701c11087b460c0cd6973b1b8fcc15a68297de62d34d2b73603696fad872d2eac0443ca3bc
      info:
        cluster: cluster/info
        metrics: metrics
        node: node/info
      rewards: false
      url:
      - https://l1-lb-testnet.constellationnetwork.io
tessellation:
  github:
    releases:
      latest: repos/constellation-labs/tessellation/releases/latest
    url: https://api.github.com
