file settings:
  locations:
    cluster modules: assets/src/cluster modules
    db: assets/data/db/database.db
    log: assets/data/logs/bot/exec.log
general:
  loop_init_time: '12:00:00'
  loop_interval_minutes: 1
  name: Hgtp Node Spidr
  notifications:
    free disk space sleep (hours): 6
    free disk space threshold (percentage): 10
    reward state sleep (minutes): 10
  public release: false
  request retry (count): 3
  request retry interval (sec): 1
  request timeout (sec): 6
  version: 5-alpha.1
modules:
  integrationnet:
    0:
      be:
        info:
          latest snapshot: global-snapshots/latest
        url:
        - https://be-integrationnet.constellationnetwork.io
      id: 3a3c367eaffa5bb3c4b35404e95983c73c522d166010784cc8d69ee9cc9c415c11534d331b70fceb7d445c96dcf62021bb8d7762a81506a0b616c45a32f00055
      info:
        cluster: cluster/info
        metrics: metrics
        node: node/info
      rewards: true
      url:
      - https://l0-lb-integrationnet.constellationnetwork.io
    1:
      id: 29b0dc8d310b0403db818db2da8d187127cdce14a825d3176534b03537e8573eaff0f95366617074996322d64f52b7a62e2737d77f7fbc888accbf4b98f7f651
      info:
        cluster: cluster/info
        metrics: metrics
        node: node/info
      rewards: false
      url:
      - https://l1-lb-integrationnet.constellationnetwork.io
  mainnet:
    0:
      be:
        info:
          latest snapshot: global-snapshots/latest
        url:
        - https://be-mainnet.constellationnetwork.io
      id: 1d5ca25f46872297ac5277089f6909751e5bff3dba8e638c34cbe9d04b7d04def083088f5a670495b83d8fb039f2e75d539546a6221373fca46a814efb9dcb06
      info:
        cluster: cluster/info
        metrics: metrics
        node: node/info
      rewards: true
      url:
      - https://l0-lb-mainnet.constellationnetwork.io
    1:
      id: 1d64061fb8eea8a5ca7dce1247dc53204ea744a2dabbcb69b3232e971407a85abc3770d73f229c3c9ddd076f1efa243e8c45f24b29b7a54041c24062fe2d84be
      info:
        cluster: cluster/info
        metrics: metrics
        node: node/info
      rewards: false
      url:
      - https://l1-lb-mainnet.constellationnetwork.io
  testnet:
    0:
      be:
        info:
          latest snapshot: global-snapshots/latest
        url:
        - https://be-testnet.constellationnetwork.io
      id: 154311944d97be83d18d37fcc3c8e7bb20cd8fa2c97e9e736f402f2614b112aa3d9ff57d6aa27b8aed82fe74b26c98c300e41b67c2c20c8d0cb1458f487adbd8
      info:
        cluster: cluster/info
        metrics: metrics
        node: node/info
      rewards: true
      url:
      - https://l0-lb-testnet.constellationnetwork.io
    1:
      id: 9561959b0b4410e263fa9d0e25ee2bfeb9a1362db6680ceef242b11f5f18e98457b1191478e5901153c9dbb6eb5eca09924d9ab210017dd203bab5816ff88567
      info:
        cluster: cluster/info
        metrics: metrics
        node: node/info
      rewards: false
      url:
      - https://l1-lb-testnet.constellationnetwork.io
tessellation:
  github:
    releases:
      latest: repos/constellation-labs/tessellation/releases/latest
    url: https://api.github.com
